version: '3.4'

services:
  database:
    container_name: mysql
    restart: always
    image: mysql:${MYSQL_VERSION}
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - ${MYSQL_EXPOSRED_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database:/var/lib/mysql
